name: grocerymart
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  intl: ^0.17.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  page_transition: ^2.0.9
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.1.3
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  hive_flutter: ^1.1.0
  dio: ^5.3.2
  freezed_annotation: ^2.2.0
  pretty_dio_logger: ^1.3.1
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  image_picker: ^1.0.1
  scrollable_positioned_list: ^0.3.8
  geolocator: ^10.0.0
  app_settings: ^5.1.1
  readmore: ^2.2.0
  flutter_staggered_animations: ^1.1.1
  dotted_line: ^3.2.2
  flutter_stripe: ^9.3.0
  http: ^1.1.0
  firebase_core: ^2.16.0
  flutter_html: ^3.0.0-beta.2
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0
  lite_rolling_switch: ^1.0.1
  intl: ^0.17.0
  intl_utils: ^2.8.5
  device_preview: ^1.1.0
  flutter_localizations:
    sdk: flutter
  pinput: ^3.0.1
  connectivity_wrapper: ^1.1.4
  flutter_cache_manager: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/font/OpenSans-Light.ttf
          weight: 300
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
