// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByRT32st6-TzsA6cLWN_OIgC8hXR3fjWI',
    appId: '1:474885582957:web:81bf85556627077d15cf64',
    messagingSenderId: '474885582957',
    projectId: 'itmicroshop',
    authDomain: 'itmicroshop.firebaseapp.com',
    storageBucket: 'itmicroshop.appspot.com',
    measurementId: 'G-6TZ5VNW6W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdNVJAm-bazlrHkApLGf-KBYSbuFc-YHA',
    appId: '1:474885582957:android:c0cf53f5a583823315cf64',
    messagingSenderId: '474885582957',
    projectId: 'itmicroshop',
    storageBucket: 'itmicroshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWFYtG8m3zjmtSsGg0jNoTnUEayzA2d_E',
    appId: '1:474885582957:ios:3a4f7b7f336df0c815cf64',
    messagingSenderId: '474885582957',
    projectId: 'itmicroshop',
    storageBucket: 'itmicroshop.appspot.com',
    iosBundleId: 'com.microlab.microshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWFYtG8m3zjmtSsGg0jNoTnUEayzA2d_E',
    appId: '1:474885582957:ios:029fa8635ab98cc815cf64',
    messagingSenderId: '474885582957',
    projectId: 'itmicroshop',
    storageBucket: 'itmicroshop.appspot.com',
    iosBundleId: 'com.grocerymart',
  );
}
